- app/build.gradle
- app/src/main/java/com/starry/myne/others/BookDownloader.kt
> fix error when downloading books with invalid chars in filename

- app/src/main/res/values-es/strings.xml
Simply added the Spanish translations
> Added Spanish translations

- .github/ISSUE_TEMPLATE/--bug-report.yml
- .github/ISSUE_TEMPLATE/--feature-request.yml
- .idea/deploymentTargetDropDown.xml
- app/src/main/java/com/starry/myne/di/MainModule.kt
- app/src/main/java/com/starry/myne/others/BookDownloader.kt
- app/src/main/java/com/starry/myne/repo/BookRepository.kt
- app/src/main/java/com/starry/myne/repo/models/Author.kt
- app/src/main/java/com/starry/myne/repo/models/Book.kt
- app/src/main/java/com/starry/myne/repo/models/BookSet.kt
- app/src/main/java/com/starry/myne/repo/models/ExtraInfo.kt
- app/src/main/java/com/starry/myne/repo/models/Formats.kt
- app/src/main/java/com/starry/myne/repo/models/Translator.kt
- app/src/main/java/com/starry/myne/ui/navigation/NavGraph.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/composables/CategoryDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/viewmodels/CategoryViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/home/composables/BookDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/home/composables/HomeScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/home/viewmodels/BookDetailViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/home/viewmodels/HomeViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/other/NetworkErrorView.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/viewmodels/ReaderDetailViewModel.kt
- app/src/main/java/com/starry/myne/utils/BookUtils.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Fix some crashes and add a retry button to request for data again on connection error

- app/src/main/java/com/starry/myne/di/MainModule.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/viewmodels/CategoryViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/home/viewmodels/BookDetailViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/home/viewmodels/HomeViewModel.kt
- app/src/main/java/com/starry/myne/utils/BookDownloader.kt
- app/src/main/java/com/starry/myne/utils/Preferencesutils.kt
> Make language choice persistent

- .github/workflows/android.yml
- .idea/kotlinc.xml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Use compose Bom instead of manually specifying versions
Upgrade to Gradle 8.1
Upgrade to Katlin 1.9.0
Update JVM target to 17
Update all of the dependencies
> Switch to KSP from KAPT

- .github/workflows/release.yml
Context: https://github.com/r0adkll/sign-android-release/issues/84
> Specify last build tools version for release CI

- app/src/main/java/com/starry/myne/epub/EpubParser.kt
- app/src/main/java/com/starry/myne/repo/BookRepository.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderDetailScreen.kt
> Fix crash due to title tag missing in opf index

- app/src/main/java/com/starry/myne/ui/screens/settings/composables/SettingsScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/welcome/composables/WelcomeScreen.kt
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-cs/strings.xml
- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-ro/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
ref: https://github.com/Pool-Of-Tears/Myne/pull/124
> Export some strings related to settings

- README.md
> Organise README

- app/src/main/java/com/starry/myne/MainActivity.kt
- app/src/main/java/com/starry/myne/MyneApp.kt
- app/src/main/java/com/starry/myne/ui/common/BookItemCard.kt
- app/src/main/java/com/starry/myne/ui/common/NetworkError.kt
- app/src/main/java/com/starry/myne/ui/navigation/NavGraph.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/composables/CategoriesScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/composables/CategoryDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/detail/composables/BookDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/home/composables/HomeScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/library/composables/LibraryScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/main/MainScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/AboutScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/OSLScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/SettingsScreen.kt
- app/src/main/res/drawable/ic_osi_logo.xml
ALso improve button colors of delete dialog
> Add animation when deleting item from library

- app/src/main/res/values-ru/strings.xml
Corrected the translation
I think Google Translator is one of the worst options for translating into Russian (as well as vice versa). For example, this comment was translated in a Yandex translator, and in my opinion it looks and reads much better (but I usually translate it myself).
> Update ru strings.xml

- README.md
- fastlane/metadata/android/en-US/full_description.txt
Add info about epub import functionality.
> Update app description

- app/src/main/java/com/starry/myne/ui/screens/home/viewmodels/HomeViewModel.kt
> Fix NPE when there is no network connection on startup

- app/build.gradle
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderContent.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/others/ReaderFont.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/viewmodels/ReaderViewModel.kt
- app/src/test/java/com/starry/myne/BookTextMapperTest.kt
- app/src/test/java/com/starry/myne/BookUtilsTest.kt
- app/src/test/java/com/starry/myne/EpubParserTest.kt
- app/src/test/java/com/starry/myne/EpubXMLFileParserTest.kt
- app/src/test/java/com/starry/myne/PaginatorTest.kt
While on that also add missing copyright headers in test files.
> fix: Fix copy popup menu not dismissing when clicking elsewhere

- app/build.gradle
- app/src/main/java/com/starry/myne/MainActivity.kt
- app/src/main/java/com/starry/myne/api/BookAPI.kt
- app/src/main/java/com/starry/myne/ui/common/TopAppBars.kt
- app/src/main/java/com/starry/myne/ui/screens/detail/composables/BookDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/home/composables/HomeScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/library/composables/LibraryScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/main/MainScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/activities/ReaderActivity.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/SettingsScreen.kt
- app/src/main/java/com/starry/myne/ui/theme/Theme.kt
While on that, also add loging intercepter in http client on debug mode
> feat: enable edge-to-edge and remove deprecated systemuicontroller

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/starry/myne/helpers/Utils.kt
- app/src/main/java/com/starry/myne/helpers/book/BookUtils.kt
- app/src/main/java/com/starry/myne/ui/screens/detail/composables/BookDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/library/composables/LibraryScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/SettingsScreen.kt
Note that this doesn't affect devices running on HyperOS, for more information, see: https://github.com/Pool-Of-Tears/GreenStash/issues/130
> fix: Disable app locale setting on MIUI due to Xiaomi's broken implementation

- .gitignore
- .idea/kotlinc.xml
- app/build.gradle
- app/src/main/java/com/starry/myne/helpers/Paginator.kt
- app/src/main/java/com/starry/myne/helpers/Utils.kt
- build.gradle
See: https://kotlinlang.org/docs/whatsnew20.html
While on that, also optimise MIUI checker function to not run on non Xiaomi devices.
> Upgrade to Kotlin 2.0

- app/src/main/java/com/starry/myne/epub/EpubParser.kt
> fix: Fix error when parsing chapters when chapter src is URL encoded

- .idea/misc.xml
- app/src/main/java/com/starry/myne/epub/EpubParser.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/activities/ReaderActivity.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderContent.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/viewmodels/ReaderViewModel.kt
- app/src/main/res/values-v27/themes.xml
- app/src/main/res/values/themes.xml
> feat: Display system bars when opening reader menu

- app/src/main/res/values-bn/strings.xml
Please go the the `Preview` tab and select the appropriate sub-template:
- [General PR](?expand=1&template=general_template.md): for all other PRs, including bug fixes, adding features etc.
- [Translation PR](?expand=1&template=translations_template.md): specifically to be used for translation PRs
> feat: added bengali translation

- .idea/appInsightsSettings.xml
- app/src/main/java/com/starry/myne/di/MainModule.kt
- app/src/main/java/com/starry/myne/epub/EpubCache.kt
- app/src/main/java/com/starry/myne/epub/EpubParser.kt
- app/src/main/java/com/starry/myne/epub/models/EpubChapter.kt
- app/src/main/java/com/starry/myne/ui/screens/library/viewmodels/LibraryViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/activities/ReaderActivity.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ChaptersContent.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/composables/ReaderScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/viewmodels/ReaderViewModel.kt
- app/src/test/java/com/starry/myne/EpubParserTest.kt
> fix: Handle one edge-case in reader & some other improvements

- app/src/main/java/com/starry/myne/epub/EpubParser.kt
- app/src/main/java/com/starry/myne/epub/cache/EpubCache.kt
- app/src/main/java/com/starry/myne/helpers/book/BookDownloader.kt
- app/src/main/java/com/starry/myne/helpers/book/BookUtils.kt
- app/src/main/java/com/starry/myne/ui/common/BookLanguageSheeet.kt
- app/src/main/java/com/starry/myne/ui/common/TopAppBars.kt
- app/src/main/java/com/starry/myne/ui/navigation/NavGraph.kt
- app/src/main/java/com/starry/myne/ui/screens/categories/composables/CategoryDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/detail/composables/BookDetailScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/detail/viewmodels/BookDetailViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/home/composables/HomeScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/library/composables/LibraryScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/library/viewmodels/LibraryViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/main/MainScreen.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/detail/ReaderDetailViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/main/activities/ReaderActivity.kt
- app/src/main/java/com/starry/myne/ui/screens/reader/main/viewmodel/ReaderViewModel.kt
- app/src/main/java/com/starry/myne/ui/screens/settings/composables/AboutScreen.kt
- app/src/test/java/com/starry/myne/EpubParserTest.kt
While on that, also disabled TOC-based EPUB parsing due to inconsistent behavior and broken chapter mapping on multiple occasions.
> fix: Fix bug where all Chinese books had same file names, also improve internal filename handling

- app/src/main/java/com/starry/myne/epub/EpubParser.kt
> fix: Fix one edge case in ToC based parsing
